# Creating constants for each field fixed width
COMPANY_NAME = 20
COMPANY_CONTACT_LAST_NAME = 20
COMPANY_CONTACT_FIRST_NAME = 15
COMPANY_STREET = 30
COMPANY_CITY = 20
COMPANY_STATE = 2
COMPANY_ZIP = 5
COMPANY_MAIN_PHONE = 10
COMPANY_ALT_PHONE = 10
ALPHA_KEY_VALUE = 10
BETA_KEY_VALUE = 28
REGION = 5
COMPANY_CODE = 7
CUSTOMER_TYPE = 1
CUSTOMER_LIMIT = 4
CUSTOMER_ID = 10

